version: '3'
services:
  web-steps:
    build:
      context: .
      dockerfile: docker/Dockerfile-project
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./node_modules:/student-management-system/node_modules
    ports:
      - '8060:8060'
    links:
      - mongo
    depends_on:
      - mongo
    image: imsunhao/student-management-system:${tag}
  mongo:
    hostname: mongo
    build:
      context: .
      dockerfile: docker/Dockerfile-mongo
    env_file:
      - ./mongodb/mongo.env
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongodb/data/log:/var/log/mongodb/\
    expose:
      - '27017'
    image: imsunhao/mongo:${tag}
