FROM node:12 as student-management-system

ENV workspace=/student-management-system

RUN mkdir -p $workspace

WORKDIR $workspace

COPY ./docker-bin/ $workspace/docker-bin/
COPY ./dist $workspace/dist
COPY ./src/index.template.html $workspace/src/
COPY ./package*.json $workspace/
COPY ./yarn.lock $workspace/
COPY ./mongodb/mongo.env $workspace/mongodb/

EXPOSE 8060

CMD ["/bin/bash", "/student-management-system/docker-bin/start.sh"]
