# 请在 template 文件 中 修改

FROM node:12 as student-management-system

ENV workspace=/student-management-system

RUN mkdir -p $workspace

VOLUME $workspace/node_modules

WORKDIR $workspace

# web-steps-copy-outlet
COPY ./docker/bin/ $workspace/bin/
COPY ./package*.json $workspace/
COPY ./mongodb/mongo.env $workspace/mongodb/

EXPOSE 8060

CMD ["/bin/bash", "/student-management-system/bin/start.sh"]
